# Generated by Django 5.2.8 on 2025-11-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
