# Generated by Django 5.2.8 on 2025-11-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
