# Generated by Django 5.2.8 on 2025-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(upload_to='media/products/'),
        ),
    ]
