# Generated by Django 5.2.8 on 2025-11-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('store', '0005_alter_product_image_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produto',
        ),
    ]
